code --install-extension steve8708.Align
code --install-extension luggage66.AWK
code --install-extension alefragnani.Bookmarks
code --install-extension wmaurer.change-case
code --install-extension formulahendry.code-runner
code --install-extension nemesv.copy-file-name
code --install-extension GrapeCity.gc-excelviewer
code --install-extension bibhasdn.git-easy
code --install-extension lukehoban.Go
code --install-extension mycelo.oracle-plsql
code --install-extension alefragnani.project-manager
code --install-extension extr0py.vscode-relative-line-numbers
code --install-extension humao.rest-client
code --install-extension vscodevim.vim
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension adamhartford.vscode-base64
code --install-extension DotJoshJohnson.xml
code --install-extension DotJoshJohnson.xml
pause