code --install-extension adamhartford.vscode-base64
code --install-extension alefragnani.Bookmarks
code --install-extension bibhasdn.git-easy
code --install-extension dbankier.vscode-instant-markdown
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension felipecaputo.git-project-manager
code --install-extension formulahendry.code-runner
code --install-extension GrapeCity.gc-excelviewer
code --install-extension luggage66.AWK
code --install-extension lukehoban.Go
code --install-extension mycelo.oracle-plsql
code --install-extension nemesv.copy-file-name
code --install-extension pprice.better-merge
code --install-extension steve8708.Align
code --install-extension wmaurer.change-case
code --install-extension xyz.plsql-language
