code --install-extension adamhartford.vscode-base64
code --install-extension adelphes.google-search-ext
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.numbered-bookmarks
code --install-extension alefragnani.project-manager
code --install-extension apng.orclapex-autocomplete
code --install-extension bibhasdn.unique-lines
code --install-extension codezombiech.gitignore
code --install-extension dbankier.vscode-quick-select
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.find-related
code --install-extension eamodio.gitlens
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension felipecaputo.git-project-manager
code --install-extension formulahendry.code-runner
code --install-extension GrapeCity.gc-excelviewer
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension humao.rest-client
code --install-extension jakeboone02.mediawiki
code --install-extension jerriepelser.copy-markdown-as-html
code --install-extension luggage66.AWK
code --install-extension lukehoban.Go
code --install-extension nemesv.copy-file-name
code --install-extension pedroguerra.ant-tree-viewer
code --install-extension ryu1kn.text-marker
code --install-extension slevesque.vscode-multiclip
code --install-extension steve8708.Align
code --install-extension wmaurer.change-case
code --install-extension wmaurer.vscode-jumpy
code --install-extension xyz.plsql-language
code --install-extension ziyasal.vscode-open-in-github
